### ISSUE TITLE
crash on ubuntu 16.04

### ISSUE THREAD

**Issue by xuraymond** [eXtremal-ik7/pool_frontend_zcash#39]
segmentation fault when zcashd syncs blockchain. Patched with pool.diff, on Ubuntu 16.04.

Thread 23 "zcashd" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffbeffd700 (LWP 4763)]
__memset_sse2 () at ../sysdeps/x86_64/multiarch/../memset.S:93
93      ../sysdeps/x86_64/multiarch/../memset.S: No such file or directory.
(gdb) bt
#0  __memset_sse2 () at ../sysdeps/x86_64/multiarch/../memset.S:93
#1  0x0000555555c3ca5c in opRingShift ()
#2  0x0000555555c3d48d in processTimeoutQueue ()
#3  0x0000555555c41596 in epollNextFinishedOperation ()
#4  0x0000555555c3bcf5 in asyncLoop ()
#5  0x0000555555c0cfd4 in poolRpcThread(void*) ()
#6  0x00007ffff7bc16ba in start_thread (arg=0x7fffbeffd700) at pthread_create.c:333
#7  0x00007ffff6a283dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

(gdb) info all-registers
rax            0x7fffb4004868   140736213305448
rbx            0x0      0
rcx            0x7fffb4021000   140736213422080
rdx            0x7fffb4003a00   140736213301760
rsi            0x0      0
rdi            0x7fffb4004868   140736213305448
rbp            0x7fffbeffb160   0x7fffbeffb160
rsp            0x7fffbeffb118   0x7fffbeffb118
r8             0x7fffbeffaff0   140736397815792
r9             0x7fffbeffb000   140736397815808
r10            0xffffffff       4294967295
r11            0x0      0
r12            0x0      0
r13            0x7fffffffbecf   140737488338639
r14            0x7fffbeffd9c0   140736397826496
r15            0x1      1
rip            0x7ffff69b02d0   0x7ffff69b02d0 <__memset_sse2+144>
eflags         0x10287  [ CF PF SF IF RF ]

gdb disas:
   0x00007ffff69b02ad <__memset_sse2+109>:      movdqu %xmm0,0x20(%rdi)
   0x00007ffff69b02b2 <__memset_sse2+114>:      movdqu %xmm0,-0x30(%rdi,%rdx,1)
   0x00007ffff69b02b8 <__memset_sse2+120>:      movdqu %xmm0,0x30(%rdi)
   0x00007ffff69b02bd <__memset_sse2+125>:      movdqu %xmm0,-0x40(%rdi,%rdx,1)
   0x00007ffff69b02c3 <__memset_sse2+131>:      add    %rdi,%rdx
   0x00007ffff69b02c6 <__memset_sse2+134>:      and    $0xffffffffffffffc0,%rdx
   0x00007ffff69b02ca <__memset_sse2+138>:      cmp    %rdx,%rcx
   0x00007ffff69b02cd <__memset_sse2+141>:      je     0x7ffff69b0274 <__memset_sse2+52>
   0x00007ffff69b02cf <__memset_sse2+143>:      nop
=> 0x00007ffff69b02d0 <__memset_sse2+144>:      movdqa %xmm0,(%rcx)
   0x00007ffff69b02d4 <__memset_sse2+148>:      movdqa %xmm0,0x10(%rcx)
   0x00007ffff69b02d9 <__memset_sse2+153>:      movdqa %xmm0,0x20(%rcx)
   0x00007ffff69b02de <__memset_sse2+158>:      movdqa %xmm0,0x30(%rcx)

zcash always crashes at the same location and stack trace (see above) after having run for several minutes to several hours.

**Comment by eXtremal-ik7** [comment]
Sorry, for long time answer.
Have you core dump for crashed zcashd ?
